parameters:
#    sf_tuts_jobeet.example.class: SfTuts\JobeetBundle\Example

services:
#    sf_tuts_jobeet.example:
#        class: %sf_tuts_jobeet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
